options:

  hpcc-version:
    type: string
    default: 5.0.0-3
    description: HPCC package version

  package-checksum:
    type: string
    default: a1a1b06886e9229cb2d01bdf8c9945e4
    description: |
      HPCC package checksum. The default value is for HPCC CE 5.0.0-3 Ubuntu
      12.04 amd64. You can get other package checksums from:
           http://hpccsystems.com/download
   
  ssh-key-public:
    type: string
    default: ""
    description: The content of public SSH Key

  ssh-key-private:
    type: string
    default: ""
    description: The content of private SSH Key



# HPCC environment variable - Do we want to define them here?

# Following are the parameters for envgen which will create environment.xml
# Reference HPCC Platform envgen usage for more details

  support-nodes:
    type: int
    default: 1
    description: Number of nodes to be used for non-Thor and non-Roxie components. The recommended value is 1.

  slaves-per-node:
    type: int
    default: 1
    description: Number of thor slaves per node. The recommended value is 1.

  roxie-ratio:
    type: float
    default: 1.0
    description: Ratio for maximum available roxie nodes, which is <number of total nodes> minus <support-nodes>. 

  thor-ratio:
    type: float
    default: 1.0
    description: Ratio for maximum available thor slave nodes, which is <number of total nodes> minus <support-nodes>. 


