#!/bin/bash -e
# config-changed occurs everytime a new configuration value is updated (juju set)

. ${CHARM_DIR}/hooks/hpcc-common

update_relation_ip_list

#juju_relation_id=$(cat ${HPCC_RELATION_ID})
#dali=$(relation-get -r $juju_relation_id dali)

#[ "$juju_relation_id" != "$dali" ] && exit

#auto_gen=$(config-get auto-gen)

