#!/bin/bash -e
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed
# This script should be idempotent.
juju-log "$JUJU_REMOTE_UNIT joined relation id: $JUJU_RELATION_ID"
#juju-log relation members:
#relation-list

. ${CHARM_DIR}/hooks/hpcc-common
save_relation_id

state=$(relation-get state $JUJU_UNIT_NAME)
if [ ! -e "${LOCAL_IP_FILE}" ]
then
   juju-log "save local ip"
   save_local_ip
fi

if [ -n "$state" ]
then
   dali=$(relation-get dali $JUJU_UNIT_NAME)
   juju-log "dali: $dali, current unit : $JUJU_UNIT_NAME"
   if [ "$dali" = "$JUJU_UNIT_NAME" ]
   then
      relation-set "state=stop" "action=config" 
   else
      relation-set "state=idle" "action=config"
      service hpcc-init stop || :
   fi
else
   relation-set "state=idle" "dali=" "action=config"
   service hpcc-init stop || :
fi
juju-log "state:$(relation-get state) action:$(relation-get action)"


#update_relation_ip_list $JUJU_REMOTE_UNIT
update_relation_ip_list


