#!/bin/bash -e
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed, modified, or broken
# This script should be idempotent.


. ${CHARM_DIR}/hooks/hpcc-common

juju-log Relation id: $JUJU_RELATION_ID, Remote unit: $JUJU_REMOTE_UNIT modified its settings
#juju-log Relation settings:
#relation-get
#juju-log Relation members:
#relation-list


dali=$(relation-get dali $JUJU_UNIT_NAME)
if [ -n "$dali" ] 
then
   dali_state=$(relation-get state ${dali})
else
   exit 0
fi

if [ "$dali" != "$JUJU_UNIT_NAME" ] && [ "$dali" != "$JUJU_REMOTE_UNIT" ]  
then
   juju-log "Ingore non-dali state change."
   exit 0
fi

state=$(relation-get state $JUJU_UNIT_NAME)
juju-log "current unit state: $state, dali: $dali, dali state: $dali_state"

if [ "$dali" = "$JUJU_UNIT_NAME" ]
then
  #juju-log "This is  dali node"
  action=$(relation-get action $JUJU_UNIT_NAME)
  juju-log "dali action: $action"
  case "$state" in
        stop)
           check_cluster_states stop,idle
           if [ ${CHECK_STATE_RC} -eq 0 ] 
           then
              service hpcc-init stop || :
              relation-set "state=$action"
           fi
           ;;
        config)
           configure_cluster
           relation-set state=ready
           check_cluster_states "ready"
           if [ ${CHECK_STATE_RC} -eq 0 ]
           then
              start_and_check
              relation-set state=start
           fi
           ;;
        ready)
           check_cluster_states "ready"
           if [ ${CHECK_STATE_RC} -eq 0 ]
           then
              start_and_check
              relation-set state=start
           fi
           ;;
        start)
           check_cluster_states "running"
           [ ${CHECK_STATE_RC} -eq 0 ]  && relation-set state=running
           ;;
        idle)
           relation-set state="$action"
           ;;
  esac
else
  #This is  not a dali node"
  case "$dali_state" in
     stop)
        if [ "$state" != "idle" ] 
        then
           service hpcc-init stop || :
           relation-set "state=idle"
        fi
        ;;
     start)
        if [ "$state" != "running" ] 
        then
           start_and_check
           relation-set "state=running"
        fi
        ;;
     config)
        if [ "$state" != "ready" ] 
        then
           configure_cluster
           relation-set "state=ready"
        fi
        ;;
  esac
fi

juju-log "leave relation-changed"

###
### If auto-gen set to 0 we need manually trigger
##  configure_cluster by running bin/config_hpcc.sh script later
###
#auto_gen=$(config-get auto-gen)
#juju-log "auto_gen $auto_gen"
#[  ${auto_gen}  -eq 0 ] && exit 0


#if [ ${auto_gen} -eq 1 ]
#then
#   configure_cluster ${TOTAL_UNITS}
#   rc=$?
#else
#   get_envgen_configuration
#   configure_cluster
#   rc=$?
#fi

#exit $rc
