#!/bin/bash
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed, modified, or broken
# This script should be idempotent.

. ${CHARM_DIR}/hooks/hpcc-common

#juju-log $JUJU_REMOTE_UNIT modified its settings
#juju-log Relation settings:
#relation-get
#juju-log Relation members:
#relation-list

TMP_FILE=/tmp/ip_file.tmp

echo "$(head -n 1  $LOCAL_IP_FILE);" > ${TMP_FILE}

TOTAL_UNITS=1
for UNIT in $(relation-list)
do
   UNIT_ADDRESS=`relation-get netAddress ${UNIT}`
   TOTAL_UNITS=$(expr ${TOTAL_UNITS} \+ 1)
   echo "${UNIT_ADDRESS};" >> "${TMP_FILE}"
done

##
## Sort IPs
##
awk '{ print length(), $0 | "sort -n" }' $TMP_FILE | awk '{ print $2 }'  > $IP_FILE

[  ${TOTAL_UNITS}  -eq 1 ] && exit 

##
## If auto-gen set to 0 we need manually trigger
#  configure_cluster by running bin/config_hpcc.sh script later
##
auto_gen=$(config-get auto-gen)
juju-log "auto_gen $auto_gen"
[  ${auto_gen}  -eq 0 ] && exit 


if [ ${auto_gen} -eq 1 ]
then
   configure_cluster ${TOTAL_UNITS}
else 
   get_envgen_configuration
   configure_cluster
fi

