#!/bin/bash
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed
# This script should be idempotent.
juju-log $JUJU_REMOTE_UNIT joined

. ${CHARM_DIR}/hooks/hpcc-common

save_local_ip

relation-set name="${HOSTNAME}" netAddress="${IP_ADDRESS}"
